
server:
  port: 8086

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/book
    username: root
    password: 1234

  sql:
    init:
      data-locations : classpath:db/initCategory.sql


